name: update_homebrew_liquibase

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update_lb_homebrew_formulae:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download Liquibase
        run: | 
          chmod +x download_liquibase.sh
          ./download_liquibase.sh
          ls

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
