name: update_homebrew_liquibase

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update_lb_homebrew_formulae:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: update_lb_hmbrew
        run: | 
          ./update_homebrew_liquibase.sh
          export VERSION="${1:-"$(curl -s https://github.com/liquibase/liquibase/releases/latest | grep -o "v.*" | sed s/'>.*'//g |  sed s/'v'//g | sed 's/"//g')"}"
          
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: lb-artifact_${VERSION}
          path: liquibase.rb
          retention-days: 5
